# Generated by Django 4.0.4 on 2022-06-15 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='movie_thumbs')),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('DRAMA', 'Drama'), ('SCI-FI', 'Ficção Científica'), ('COMEDY', 'Comédia'), ('OTHERS', 'Outros')], max_length=25)),
                ('number_views', models.IntegerField(default=0)),
                ('criation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
